import QRCode from 'qrcode';

const STORIE_URL = 'https://ail-ay2526-s2-samuel-storie.vercel.app/';
const CLUB_URL = 'https://smubia.com';
const WIDTH = 1600;
const HEIGHT = 2000;

function loadImage(src) {
  return new Promise((resolve, reject) => {
    const image = new Image();
    image.crossOrigin = 'anonymous';
    image.onload = () => resolve(image);
    image.onerror = reject;
    image.src = src;
  });
}

function drawImageCover(ctx, image, x, y, width, height) {
  const scale = Math.max(width / image.width, height / image.height);
  const sourceWidth = width / scale;
  const sourceHeight = height / scale;
  const sourceX = (image.width - sourceWidth) / 2;
  const sourceY = (image.height - sourceHeight) / 2;
  ctx.drawImage(image, sourceX, sourceY, sourceWidth, sourceHeight, x, y, width, height);
}

function wrapText(ctx, text, x, y, maxWidth, lineHeight, maxLines = 12) {
  const words = String(text || '').split(/\s+/);
  let line = '';
  let lines = 0;
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (ctx.measureText(candidate).width > maxWidth && line) {
      ctx.fillText(line, x, y + lines * lineHeight);
      line = word;
      lines += 1;
      if (lines >= maxLines) return;
    } else {
      line = candidate;
    }
  }
  if (line && lines < maxLines) ctx.fillText(line, x, y + lines * lineHeight);
}

function baseCanvas() {
  const canvas = document.createElement('canvas');
  canvas.width = WIDTH;
  canvas.height = HEIGHT;
  const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#f4f1e8';
  ctx.fillRect(0, 0, WIDTH, HEIGHT);
  ctx.strokeStyle = '#4a3728';
  ctx.lineWidth = 18;
  ctx.strokeRect(34, 34, WIDTH - 68, HEIGHT - 68);
  return { canvas, ctx };
}

async function makePageCard(storybook, page) {
  const { canvas, ctx } = baseCanvas();

  ctx.fillStyle = '#4a3728';
  ctx.font = '700 68px Georgia, serif';
  ctx.fillText(storybook.title, 90, 130, WIDTH - 180);
  ctx.fillStyle = '#8b7355';
  ctx.font = '38px Courier New, monospace';
  ctx.fillText(`A story for ${storybook.child_name || 'someone special'}`, 92, 190);

  const imageTop = 245;
  const imageHeight = 1010;
  ctx.fillStyle = '#d4c4a8';
  ctx.fillRect(70, imageTop, WIDTH - 140, imageHeight);
  if (page.image_url) {
    try {
      const image = await loadImage(page.image_url);
      drawImageCover(ctx, image, 70, imageTop, WIDTH - 140, imageHeight);
    } catch {
      ctx.fillStyle = '#8b7355';
      ctx.font = '48px Georgia, serif';
      ctx.textAlign = 'center';
      ctx.fillText('Imagine the scene here...', WIDTH / 2, imageTop + imageHeight / 2);
      ctx.textAlign = 'left';
    }
  }
  ctx.strokeStyle = '#4a3728';
  ctx.lineWidth = 12;
  ctx.strokeRect(70, imageTop, WIDTH - 140, imageHeight);

  ctx.fillStyle = '#a65d3f';
  ctx.font = '700 34px Courier New, monospace';
  ctx.fillText(String(page.act_title || `Page ${page.page_number}`).toUpperCase(), 90, 1335);
  ctx.fillStyle = '#4a3728';
  ctx.font = '44px Georgia, serif';
  wrapText(ctx, page.text_content, 90, 1415, WIDTH - 180, 60, 8);

  ctx.fillStyle = '#8b7355';
  ctx.font = '30px Courier New, monospace';
  ctx.fillText(`STORIE  •  PAGE ${page.page_number}`, 90, 1915);
  return canvas;
}

async function makeAboutCard(storybook) {
  const { canvas, ctx } = baseCanvas();
  ctx.textAlign = 'center';
  ctx.fillStyle = '#c9a227';
  ctx.font = '100px Georgia, serif';
  ctx.fillText('✦', WIDTH / 2, 240);
  ctx.fillStyle = '#4a3728';
  ctx.font = '700 92px Georgia, serif';
  ctx.fillText('Made with Storie', WIDTH / 2, 370);
  ctx.fillStyle = '#8b7355';
  ctx.font = '42px Courier New, monospace';
  ctx.fillText(`“${storybook.title}”`, WIDTH / 2, 450, WIDTH - 180);

  ctx.fillStyle = '#4a3728';
  ctx.font = '48px Georgia, serif';
  wrapText(
    ctx,
    'This story was generated by Storie, an AI Lodge project by the SMU Business Intelligence and Analytics club.',
    WIDTH / 2,
    570,
    WIDTH - 240,
    68,
    5,
  );

  const [storieQr, clubQr] = await Promise.all([
    loadImage(await QRCode.toDataURL(STORIE_URL, { width: 420, margin: 1, color: { dark: '#4a3728', light: '#f4f1e8' } })),
    loadImage(await QRCode.toDataURL(CLUB_URL, { width: 420, margin: 1, color: { dark: '#4a3728', light: '#f4f1e8' } })),
  ]);
  ctx.drawImage(storieQr, 190, 930, 440, 440);
  ctx.drawImage(clubQr, 970, 930, 440, 440);

  ctx.fillStyle = '#a65d3f';
  ctx.font = '700 35px Courier New, monospace';
  ctx.fillText('MAKE ANOTHER STORY', 410, 1435);
  ctx.fillText('MEET SMU BIA', 1190, 1435);
  ctx.fillStyle = '#4a3728';
  ctx.font = '25px Courier New, monospace';
  wrapText(ctx, STORIE_URL, 410, 1490, 570, 36, 3);
  wrapText(ctx, CLUB_URL, 1190, 1490, 570, 36, 3);

  ctx.fillStyle = '#8b7355';
  ctx.font = '32px Georgia, serif';
  ctx.fillText('May every ending lead to another beginning.', WIDTH / 2, 1810);
  return canvas;
}

function canvasBlob(canvas) {
  return new Promise((resolve, reject) => {
    canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error('Could not prepare this page.'))), 'image/png');
  });
}

function saveBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}

function safeName(value) {
  return String(value || 'storybook').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 48) || 'storybook';
}

export async function downloadStoryImages(storybook) {
  const pages = [...(storybook.pages || storybook.story_pages || [])]
    .sort((a, b) => a.page_number - b.page_number);
  const canvases = [];
  for (const page of pages) canvases.push(await makePageCard(storybook, page));
  canvases.push(await makeAboutCard(storybook));

  const prefix = safeName(storybook.title);
  for (let index = 0; index < canvases.length; index += 1) {
    const suffix = index === canvases.length - 1 ? 'about' : String(index + 1).padStart(2, '0');
    saveBlob(await canvasBlob(canvases[index]), `${prefix}-${suffix}.png`);
    await new Promise((resolve) => setTimeout(resolve, 180));
  }
}
